project:
  type: website

website:
  title: "TUMO boxes climate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: source1.qmd
        text: Sources
      - about.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
