---
title: "TUMO boxes climate"
execute: 
  echo: false
  warning: false
---

```{r, echo=FALSE, message=FALSE}
#| message: false

#| echo: false

#| label: setup

library(tidyverse)
library(lubridate)
library(ggplot2)
```

```{r, echo=FALSE, message=FALSE}
data <- read_csv("vazgen.csv")
data2 <- read_csv("sevan.csv")
data3 <- read_csv("maralik.csv")
data4 <- read_csv("gavar.csv")
data5 <- read_csv("ashotsk.csv")
data6 <- read.csv("artik.csv")

```

```{r, echo=FALSE, message=FALSE}

library(tidyverse)
library(lubridate)  

data <- read.csv("vazgen.csv")

data$time <- as.Date(data$time)

data <- data %>%
  mutate(season = case_when(
    month(time) %in% 3:5 ~ "Spring",
    month(time) %in% 6:8 ~ "Summer",
    month(time) %in% 9:11 ~ "Autumn",
    month(time) %in% c(12, 1, 2) ~ "Winter"
  ))

data <- data %>%
  mutate(day_of_year = yday(time))

p <- ggplot(data, aes(x=time, y=temperature, color=season)) +
  geom_line() +
  scale_x_continuous(breaks = c(1, 91, 182, 274), labels = c("Winter", "Spring", "Summer", "Autumn")) +
  labs(title = "Temperature Over Time by Season",
       x = "Day of Year",
       y = "Temperature",
       subtitle = "I divided database info into seasons",
       color = "Season") +
  theme_minimal() +
  coord_polar(theta = "x")

print(p)

```

```{r, echo=FALSE}

library(tidyverse)
library(lubridate)  

data <- read.csv("sevan.csv")  


data$time <- as.Date(data$time)

data <- data %>%
  mutate(season = case_when(
    month(time) %in% 3:5 ~ "Spring",
    month(time) %in% 6:8 ~ "Summer",
    month(time) %in% 9:11 ~ "Autumn",
    month(time) %in% c(12, 1, 2) ~ "Winter"
  ))

data <- data %>%
  mutate(day_of_year = yday(time))

p <- ggplot(data, aes(x = time, y = temperature, color = season)) +
  geom_line() +
  scale_x_continuous() +
  labs(title = "Temperature Over Time by Season In Sevan",
       x = "Day of Year",
       y = "Temperature",
       subtitle = "In Sevan, Climatenet worked only in summer, so it only claimed info about summer",
       color = "Season") +
  theme_minimal() +
  coord_polar(theta = "x")

print(p)


```



```{r}

library(ggplot2)
library(plotly)
library(gapminder)

data4 <-  read_csv("gavar.csv")
data3 <- read_csv("maralik.csv")


combined <- rbind(data4,data3)

p <- combined %>%
ggplot(aes(time, pressure , size = temperature, color=device)) +
  geom_point() +
  theme_bw() +
  labs(title = "Temperature, Pressure Over Time In Gavar & Maralik",
       caption = "I combined data about Gavar & Maralik. You can choose some part of chart." )
  # ggtitle("Temperature, Pressure Over Time In Gavar & Maralik") 
ggplotly(p)




```

       I combined data about Gavar & Maralik. You can choose some part of chart.



```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(babynames)
library(viridis)
library(hrbrthemes)
library(plotly)

data5 <- read_csv("ashotsk.csv")
data5 <- data5 %>%
  select("pressure", "humidity", "pm2_5", "temperature", "time")

p <- data5 %>%
ggplot(aes(x = time, y = temperature, fill = pressure, fill = humidity )) +
  geom_area() +
  theme(legend.position = "none") +
  ggtitle("Temperature Over Time In Ashotsk") +
  scale_fill_gradient(low = "yellow")

p <- ggplotly(p, tooltip = c("x", "y", "fill"))

p



```


    Here, you can see Ashotsk data. If you put your coursor on chart, you can see time, temperature, pressure and speed.





    Under here, it's also Ashotsk data. Here you can see air quality in different indicators.





```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(reshape2)
library(plotly)


data <- read.csv("artik.csv")

data$time <- as.POSIXct(data$time, format="%Y-%m-%d %H:%M:%S")

data_long <- melt(data, id.vars = "time", measure.vars = c("pm1", "pm2_5", "pm10"))

plot_pm1 <- ggplot(subset(data_long, variable == "pm1"), aes(x = time, y = value)) +
  geom_hex(bins = 70) +
  scale_fill_viridis_c() +
  labs(title = "
    Air quality in Ashotsk.   Hexbin Plot for PM1
       ", x = "Time", y = "PM1") +
  theme_bw()

interactive_pm1 <- ggplotly(plot_pm1)

plot_pm2_5 <- ggplot(subset(data_long, variable == "pm2_5"), aes(x = time, y = value)) +
  geom_hex(bins = 70) +
  scale_fill_viridis_c() +
  labs(title = "Hexbin Plot for PM2.5", x = "Time", y = "PM2.5") +
  theme_bw()

interactive_pm2_5 <- ggplotly(plot_pm2_5)

plot_pm10 <- ggplot(subset(data_long, variable == "pm10"), aes(x = time, y = value)) +
  geom_hex(bins = 70) +
  scale_fill_viridis_c() +
  labs(title = "Hexbin Plot for PM10", x = "Time", y = "PM10") +
  theme_bw()

interactive_pm10 <- ggplotly(plot_pm10)

interactive_pm1
interactive_pm2_5
interactive_pm10


```




```{r, echo=FALSE, message=FALSE}


library(ggplot2)

data <- read.csv("artik.csv")
plot8 <- ggplot(data, aes(x=time, y=speed)) +
  geom_point(color="blue") +
  geom_smooth(method="lm", se=FALSE, color="red") +
  labs(
    x = "Time",
    y = "Speed",
    title = "Distribution Between Speed and Time"
  ) +
  theme_minimal()


```



























